%	OVERVIEW:
%       This basic demo will allow to investigate the effect of noise on
%       HRV analysis and how different strategies to deal with noise
%       leads to different results
%
%   DEPENDENCIES & LIBRARIES:
%       https://github.com/cliffordlab/PhysioNet-Cardiovascular-Signal-Toolbox
%   REFERENCE: 
%       Vest et al. "An Open Source Benchmarked HRV Toolbox for Cardiovascular 
%       Waveform and Interval Analysis" Physiological Measurement (In Press), 2018. 
%	REPO:       
%       https://github.com/cliffordlab/PhysioNet-Cardiovascular-Signal-Toolbox
%   ORIGINAL SOURCE AND AUTHORS:     
%       Giulia Da Poian   
%	COPYRIGHT (C) 2019 
%   LICENSE:    
%       This software is offered freely and without warranty under 
%       the GNU (v3 or later) public license. See license file for
%       more information
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

clear all
clc

% Remove old files generated by this demo
OldFolder = [pwd,filesep, 'results'];
if exist(OldFolder, 'dir')
    rmdir(OldFolder, 's');
    fprintf('Old Demo Folder deleted \n \n');
end


% Initialize the HRV parameters
HRVparams = InitializeHRVparams_workshop('demo_workshop');

% Where are the data, in this demo they are located in a subfolder
InputFolder = [pwd filesep 'workshop_data']; % path to the folder where you data are located
SigName = '118';

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% 1. Signal without added noise

    % load a clean  ecg signal using load (it loads a variable called val)
    load([InputFolder filesep SigName]);
    % the signal has two channels, from now on we will use just one 
    ecg = val(:,1);
    % time vector for visualization (in seconds)
    tm = 0:1/HRVparams.Fs:(length(ecg)-1)/HRVparams.Fs;

    % plot the signal
    figure(1)
    plot(tm,ecg);
    xlabel('[s]');
    ylabel('[mV]')

    % band-pass filter
    ecg_filt = bp_filter_005_40_ECG(ecg, HRVparams.Fs);

    % Detection of the R-peaks and SQI analysis 
    % note that additional QRS annotations generated by different detector are saved in the results folder 
    [trr_jqrs,rr_jqrs,jqrs_ann,SQIjw, StartSQIwindows_jw] = ConvertRawDataToRRIntervals(ecg_filt ,HRVparams, SigName);

    sqi = [StartSQIwindows_jw', SQIjw'];
    
    % load for example jqrs annotations (note position is in samples not secons)
    r_jqrs = read_ann([HRVparams.writedata filesep 'Annotation' filesep SigName], 'jqrs');
    % and wqrs annotations (sensitive to noise)
    r_wqrs = read_ann([HRVparams.writedata filesep 'Annotation' filesep SigName], 'wqrs');

    % plot the detected jqrs r_peaks on the top of the ecg signal
    close all
    Plot_SignalDetection_SQI(tm, ecg_filt, r_jqrs, SQIjw, 'ECG')
    
    % Perform HRV analysis using RR intervals derived from jqrs r_peaks
    [HRVout, ResultsFileName ] = Main_HRV_Analysis(rr_jqrs,trr_jqrs,'RRIntervals',HRVparams,SigName,[],sqi);
    
    % load results in a table 
    hrv_results_clean = readtable([HRVparams.writedata filesep '118_HRV_results_allwindows_.csv']);
    
    
%  %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% 2. Signal with added artificial noise (SNR 6db)

    % load a clean  ecg signal using load (it loads a variable called val)
    load([InputFolder filesep SigName 'e06']);
    % the signal has two channels, from now on we will use just one 
    ecg_6db = val(:,1);
    % time vector for visualization (in seconds)
    tm = 0:1/HRVparams.Fs:(length(ecg_6db)-1)/HRVparams.Fs;

    % plot the signal
    close all
    plot(tm,ecg_6db);
    xlabel('[s]');
    ylabel('[mV]')

    % band-pass filter
    ecg_filt_6db = bp_filter_005_40_ECG(ecg_6db, HRVparams.Fs);

    % Detection of the R-peaks and SQI analysis 
    % note that additional QRS annotations generated by different detector are saved in the results folder 
    [trr_jqrs,rr_jqrs,jqrs_ann,SQIjw, StartSQIwindows_jw] = ConvertRawDataToRRIntervals(ecg_filt_6db ,HRVparams, [SigName  'e06']);

    sqi = [StartSQIwindows_jw', SQIjw'];
    
    % load for example jqrs annotations (note position is in samples not secons)
    r_jqrs = read_ann([HRVparams.writedata filesep 'Annotation' filesep [SigName  'e06']], 'jqrs');
    % and wqrs annotations (sensitive to noise)
    r_wqrs = read_ann([HRVparams.writedata filesep 'Annotation' filesep [SigName  'e06']], 'wqrs');

    % plot the detected jqrs r_peaks on the top of the ecg signal
    close all
    Plot_SignalDetection_SQI(tm, ecg_filt_6db, r_jqrs, SQIjw, 'ECG')
    
    % Perform HRV analysis using RR intervals derived from jqrs r_peaks
    [HRVout, ResultsFileName ] = Main_HRV_Analysis(rr_jqrs,trr_jqrs,'RRIntervals',HRVparams,[SigName  'e06_SQI'],[],sqi);
    
    % load results in a table 
    hrv_results_6db = readtable([HRVparams.writedata filesep '118e06_SQI_HRV_results_allwindows_.csv']);

%% 3. Derived HRV from the noisy signal without considering SQI

    % Perform HRV analysis using RR intervals derived from jqrs r_peaks
    [HRVout, ResultsFileName ] = Main_HRV_Analysis(rr_jqrs,trr_jqrs,'RRIntervals',HRVparams,[SigName  'e06_noSQI'],[],[]);
    
    % load results in a table 
    hrv_results_6db_noSQI = readtable([HRVparams.writedata filesep '118e06_noSQI_HRV_results_allwindows_.csv']);

%% 4. Compare differences in HRV measures in the three cases, making the 
%     assumption that HRV measures from poin 1 are the gold standard

      % low frequency lf
      out_lf_mtx = [hrv_results_clean.lf  hrv_results_6db.lf hrv_results_6db_noSQI.lf];
      figure(111)
      bar(out_lf_mtx,'DisplayName','LF [ms^2]')
      legend({'Original','Noisy only good SQI','Noisy all SQI'})
      title('Comparison of LF values')
    
    